application:
  port: 8000
  host: 0.0.0.0
  base_url: "http://127.0.0.1"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "allinonenews"
  require_ssl: false
